name: Pull Request Build

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checking out for ${{ github.ref }}
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Fetch Base Branch
        run: |
          git fetch origin main
      - name: Run Danger JS
        working-directory: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx danger ci --dangerfile dangerfile.js --base main
          if [ $? -ne 0 ]; then exit $?; fi
        shell: bash
        
      - name: Install packages
        run: npm install

      - name: Compile 
        run: npm run build:tsc

      - name: Run tests
        run: npm run test

      - name: Run ESLint
        run: npm run lint